feat: Implement dynamic left and right prompt prefix options
reobin/typewritten pull request #150
Opened 2022-10-10 14:01 UTC by reobin

4 "new" options were implemented:

- `TYPEWRITTEN_LEFT_PROMPT_PREFIX` (existed before)
- `TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION`
- `TYPEWRITTEN_RIGHT_PROMPT_PREFIX`
- `TYPEWRITTEN_RIGHT_PROMPT_PREFIX_FUNCTION`

The `_FUNCTION` variants are used to enable the use of live evaluated functions as prefixes.

Example of use in `.zshrc` to display kube context:

```sh
display_kube_context() {
  tw_kube_context="$(kubectl config current-context 2&>1 /dev/null)"

  if [[ $tw_kube_context != "" ]]; then
    echo "($(basename $tw_kube_context))"
  fi
}

export TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION=display_kube_context
```

2022-10-10 14:03 UTC, reobin commented
Hello @KEDLogic ! If you have the chance to review this PR, it would be greatly appreciated. Especially the example snippet for kube context.

2022-10-11 04:34 UTC, KEDLogic commented
Oh, very nice! I'll carve out some time tomorrow to go over this. 

In case I somehow miss it when I review, the `2&>1` in that snippit needs to changed to `2>&1`. 

That bug of mine caused a fun little hunt for the source of all the `1` files throughout my file system...

2022-10-11 05:25 UTC, KEDLogic commented
I gave it a quick test and it looks good! 

That snippet needs a small edit for the error redirect (My original script had an error): 
```
display_kube_context() {
  tw_kube_context="$(kubectl config current-context 2> /dev/null)"

  if [[ $tw_kube_context != "" ]]; then
    echo "($(basename $tw_kube_context))"
  fi
}

export TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION=display_kube_context
```

2022-10-11 05:39 UTC, KEDLogic requested changes
Looks good! 
It just needs a small edit to the kubecontext snippet as noted.

2022-10-11 05:39 UTC, KEDLogic commented on docs/prompt_customization.md
> +  tw_kube_context="$(kubectl config current-context 2&>1 /dev/null)"
The error redirect should be: 
```
  tw_kube_context="$(kubectl config current-context 2> /dev/null)"
```

2022-10-13 05:18 UTC, KEDLogic approved these changes

2022-10-19 13:36 UTC, merged

2022-10-19 13:41 UTC, reobin commented
@all-contributors please add @KEDLogic for documentation and ideas